# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-01 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailganer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(),
        ),
    ]
